### ISSUE TITLE
Reconsider refs terminology

### ISSUE THREAD

**Issue by sergiimk** [open-data-fabric/open-data-fabric#42]
Borrowed git terminology is getting a bit confusing in combination with streams:
- is `head` a beginning of a stream or it's end?
- if latter, why `tail` command shows events closes to the `head`?
- how do we name an interval of blocks and in which order `[startBlock, endBlock]` are defined?

We could use better terms.

**Comment by zaychenko-sergei** [comment]
I think we should preserve `head` as in Git to avoid large number of implementation changes.
1) It's much cheaper to rename `kamu tail` command to `kamu head`.
2) Regarding intervals, call it `[earlierBlock, laterBlock]` or somehow else, indicating the flow of time.

**Comment by sergiimk** [comment]
After some discussions and thinking we decided not to rush this change.

- The "head" reference is familiar to people from Git, which is nice
- The analogy of an append log as a "snake that moves towards where its head is" seems reasonable
- We will have to either:
  - bear the inconsistency of `kamu tail` command with the `head` reference
  - or rename command to `kamu head` and instead bear the inconsistency with Linux `tail` command semantics
